### ISSUE TITLE
inline missing on line 166.

### ISSUE THREAD

**Issue by degski** [mattreecebentley/plf_nanotimer#1]
inline missing on line 166.

**Comment by mattreecebentley** [comment]
The strategy I was going for here is the two calling functions for each of the four triumvirates of functions get inlined, the main called functions don't. It makes a small but repeatable difference in benchmarking  (slightly faster) and code size (slightly larger), which surprises me, because I thought compilers mostly ignored the inline keyword nowadays, but apparently not. This is under GCC, and my benchmarks may not represent all benchmarks.

The reason I think this works is that it somewhat reduces cache load by having one location for the repeatedly-called function, rather than additional code in multiple locations. This offsets the cost of calling the function I believe.

**Comment by degski** [comment]
On 25 February 2018 at 16:11, mattreecebentley <notifications@github.com>
wrote:

> The strategy I was going for here is the two calling functions for each of
> the four triumvirates of functions get inlined, the main called functions
> don't. It makes a small but repeatable difference in benchmarking (slightly
> faster) and code size (slightly larger), which surprises me, because I
> thought compilers mostly ignored the inline keyword nowadays, but
> apparently not. This is under GCC, and my benchmarks may not represent all
> benchmarks.
>
The problem with the inline keyword is that it is not what it pretends to
be (your interpretation). The inline keyword in this header has the effect
that the *non-templated free function* *(defined in a header file)* can be
included in more than one TU. *As if* it were inlined!!!

The VC-linker signals a double definition without the inline keyword. This
is a warning, and the warning says the second definition will be ignored
(and can be ignored, in bigger and more complex setups, one might not be so
sure this is a good idea). GCC just ignores it, apparently (maybe not with
higher warning levels), without warning about it. I think you are right
about compilers ignoring the inline keyword regarding whether it should or
should not literally inline the function (mostly)... so, that's why I said
above: "As If..."...

From what I understood how GCC works is that for inlining a threshold (of
some scalar) is defined over which the function will not be inlined.
Forcing inlining (a compiler option, if I'm right) will up the threshold
(so it does it mostly), but will still obey the higher threshold and will
therefore not inline in certain cases.

degski

**Comment by mattreecebentley** [comment]
Okay, I've never had a warning from VC about nanotimer - which version
of VC are you using? But more specifically, what situations is it
doing it in? I guess my stuff has been basic benchmarking, with only
one .cpp using nanotimer.

**Comment by degski** [comment]
On 26 February 2018 at 16:01, mattreecebentley <notifications@github.com>
wrote:

> ... I guess my stuff has been basic benchmarking, with only
> one .cpp using nanotimer.
>

This ("only one .cpp") is why you did not spot it. One .cpp makes one
translation unit (TU), so there will never be a double definition (because
of the include guards in the headers). If you would have 2 or more .cpp in
one application, that both include nanotimer, then you will see the
warning. The above is supposed to work like that.

If you want that function (possibly) not inlined, you'll have to add
nanotimer.cpp and define the function in there, while nanotimer.hpp should
just include the declaration (the signature of the function). ...Or of
course you can just add the inline keyword in the header and trust that the
compiler does the right thing (you have no control over it anyway, bar
writing the thing in (inline) assembler)... Last option is to turn those
functions into templated functions (float/double), and they are guaranteed
to be inlined.

degski

**Comment by mattreecebentley** [comment]
Gotcha - tested and that's correct, fixed. Goddamn C++'s hegemony of archaic rules ;)

**Comment by degski** [comment]
On 28 February 2018 at 17:46, mattreecebentley <notifications@github.com>
wrote:

> Gotcha - tested and that's correct, fixed. Goddamn C++'s hegemony of
> archaic rules ;)
>
The inline keyword could really do with a touch-up in the std.

degski
