### ISSUE TITLE
ifdef and endif scope issue

### ISSUE THREAD

**Issue by HSNB** [mattreecebentley/plf_nanotimer#3]
At the end of the file, regarding the #endif that belongs to this #if:

#if defined(__MACH__) || (defined(linux) || defined(__linux__) || defined(__linux)) || (defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)) || defined(_WIN32)

it should be before "} // namespace", not after

**Comment by mattreecebentley** [comment]
No, it shouldn't.
The namespace { is introduced in the ifdef sections above that one.
